### ISSUE TITLE
error after installation

### ISSUE THREAD

**Issue by casualwriter** [cosin2077/chaty#17]
install node-v18.15.0-x64.msi, and no problem when install package.
run "chaty" but encountered the following error. Please help, thanks,

~~~
C:\user\nodejs>npm i -g ichaty

changed 137 packages in 5s

20 packages are looking for funding
  run `npm fund` for details

C:\nodejs>chaty
C:\Users\user\AppData\Roaming\npm\node_modules\ichaty\node_modules\fs-extra\lib\index.js:5
  ...require('./fs'),
  ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\ichaty\lib\src\main\prepare\dir.js:3:18)
~~~

**Comment by casualwriter** [comment]
just reboot pc, and work fine.  sorry for disturbing

nice program, thanks,
