### ISSUE TITLE
扫码后报错

### ISSUE THREAD

**Issue by Eloco** [cosin2077/chaty#21]
请问扫码后这个报错是啥原因
```
❯ chaty run wechat

runWechatService...
✔ install pkgs for wechat service succeed!
\ starting build pkgs for wechat service......
> chaty-wechat-service@0.1.4 build
> tsc


✔ build pkgs for wechat service succeed!

> chaty-wechat-service@0.1.4 start
> node dist/index

[qrcode]

uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/home/xxx/.npm/lib/node_modules/ichaty/lib/src/services/wechat/node_modules/wechat4u/lib/util/global.js:69:24)
    at /home/xxx/.npm/lib/node_modules/ichaty/lib/src/services/wechat/node_modules/wechat4u/lib/core.js:227:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/home/xxx/.npm/lib/node_modules/ichaty/lib/src/services/wechat/node_modules/wechat4u/lib/util/global.js:69:24)\n' +
    '    at /home/xxx/.npm/lib/node_modules/ichaty/lib/src/services/wechat/node_modules/wechat4u/lib/core.js:227:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
```

**Comment by cosin2077** [comment]
[issues/2](https://github.com/cosin2077/chaty/issues/2) 请确保实名认证过了

**Comment by Eloco** [comment]
对的，通过了就好了，谢谢
