### ISSUE TITLE
微信扫码成功后，报错

### ISSUE THREAD

**Issue by dadaoerv** [cosin2077/chaty#26]
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/usr/local/lib/nodejs/node-v18.15.0-linux-arm64/lib/node_modules/ichaty/lib/src/services/wechat/node_modules/wechat4u/lib/util/global.js:69:24)
    at /usr/local/lib/nodejs/node-v18.15.0-linux-arm64/lib/node_modules/ichaty/lib/src/services/wechat/node_modules/wechat4u/lib/core.js:227:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/usr/local/lib/nodejs/node-v18.15.0-linux-arm64/lib/node_modules/ichaty/lib/src/services/wechat/node_modules/wechat4u/lib/util/global.js:69:24)\n' +
    '    at /usr/local/lib/nodejs/node-v18.15.0-linux-arm64/lib/node_modules/ichaty/lib/src/services/wechat/node_modules/wechat4u/lib/core.js:227:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'

**Comment by dadaoerv** [comment]
知道了，是实名的问题。请关闭
