### ISSUE TITLE
微信登录报错：Cannot read properties of undefined (reading 'status')

### ISSUE THREAD

**Issue by second-curve-engineer** [cosin2077/chaty#8]
`uncaughtException GError [TypeError]: Cannot read properties of undefined (reading 'status')
    at /opt/homebrew/lib/node_modules/ichaty/lib/src/services/wechat/node_modules/wechat4u/lib/core.js:170:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: "TypeError: Cannot read properties of undefined (reading 'status')\n" +
    '    at /opt/homebrew/lib/node_modules/ichaty/lib/src/services/wechat/node_modules/wechat4u/lib/core.js:170:30\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}`

node: v16.15.0
macOS: 13.2.1

**Comment by cosin2077** [comment]
请检查下是否是网络问题
